language: node_js

node_js:
  - "stable"

sudo: false

install:
  - npm install

after_script:
  - git config user.name malcolmyu
  - git config user.email minghao_yu@163.com
  - sed -i "s/GH_TOKEN/${GH_TOKEN}/g" ./_config.yml
  - hexo d
